import { createElement } from '@lwc/engine-dom';
import GetRelatedListRecords_noApex_lds from 'c/getRelatedListRecords_noApex_lds';

describe('c-get-related-list-records-no-apex-lds', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-get-related-list-records-no-apex-lds', {
            is: GetRelatedListRecords_noApex_lds
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});